require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');

const products = [
  // Men's products
  {
    title: 'Premium Silk Boxers',
    description: 'Ultra-soft silk boxers with elastic waistband for ultimate comfort.',
    price: 899,
    compareAtPrice: 1099,
    sku: 'SILK-BOX-001',
    stock: 150,
    images: ['/assets/products/men/img1.jpg'],
    categories: ['Men', 'Underwear'],
    tags: ['silk', 'premium', 'comfort'],
    gender: 'men',
    productType: 'Boxers',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'White'],
    fabric: 'Silk Blend',
    material: 'Silk/Spandex',
    care: 'Hand wash, lay flat to dry',
    fit: 'Regular',
    pattern: 'Solid',
    supportLevel: 'Medium',
    padding: 'None',
    wireType: 'None',
    brand: 'SilkComfort',
    seo: { title: 'Premium Silk Boxers', description: 'Ultra-soft silk boxers for men.' },
    published: true,
    featured: false,
  },
  {
    title: 'Cotton Briefs Pack (5)',
    description: 'Classic cotton briefs in a 5-pack. Breathable and durable.',
    price: 699,
    compareAtPrice: 899,
    sku: 'COTTON-BRIEF-005',
    stock: 200,
    images: ['/assets/products/men/img2.jpg'],
    categories: ['Men', 'Underwear'],
    tags: ['cotton', 'classic', 'value-pack'],
    gender: 'men',
    productType: 'Briefs',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Grey'],
    fabric: 'Pure Cotton',
    material: 'Cotton',
    care: 'Machine wash warm',
    fit: 'Regular',
    pattern: 'Solid',
    supportLevel: 'Low',
    padding: 'None',
    wireType: 'None',
    brand: 'BasicComfort',
    seo: { title: 'Cotton Briefs 5-Pack for Men', description: 'Breathable cotton briefs in value pack.' },
    published: true,
    featured: false,
  },
  {
    title: 'Thermal Innerwear Set',
    description: 'Warm thermal set perfect for winter, with moisture-wicking properties.',
    price: 1299,
    compareAtPrice: 1599,
    sku: 'THERMAL-SET-001',
    stock: 80,
    images: ['/assets/products/men/img3.jpg'],
    categories: ['Men', 'Innerwear'],
    tags: ['thermal', 'winter', 'warm'],
    gender: 'men',
    productType: 'Thermal Set',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Grey'],
    fabric: 'Thermal Blend',
    material: 'Polyester/Spandex',
    care: 'Machine wash cold',
    fit: 'Fitted',
    pattern: 'Solid',
    supportLevel: 'Medium',
    padding: 'None',
    wireType: 'None',
    brand: 'WarmCore',
    seo: { title: 'Thermal Innerwear Set for Men', description: 'Warm thermal innerwear perfect for cold weather.' },
    published: true,
    featured: true,
  },
  {
    title: 'Microfiber Trunk',
    description: 'Lightweight microfiber trunk with ergonomic design.',
    price: 549,
    compareAtPrice: 699,
    sku: 'MICRO-TRUNK-001',
    stock: 250,
    images: ['/assets/products/men/img4.jpg'],
    categories: ['Men', 'Underwear'],
    tags: ['microfiber', 'lightweight', 'ergonomic'],
    gender: 'men',
    productType: 'Trunk',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Grey', 'White'],
    fabric: 'Microfiber',
    material: 'Microfiber',
    care: 'Machine wash warm, tumble dry low',
    fit: 'Slim',
    pattern: 'Solid',
    supportLevel: 'High',
    padding: 'Light',
    wireType: 'None',
    brand: 'MicroElite',
    seo: { title: 'Microfiber Trunk for Men', description: 'Lightweight ergonomic microfiber trunk.' },
    published: true,
    featured: false,
  },
  {
    title: 'Classic Men Brief',
    description: 'Classic men brief with soft fabric.',
    price: 499,
    compareAtPrice: 599,
    sku: 'CLASSIC-BRIEF-001',
    stock: 180,
    images: ['/assets/products/men/img5.jpg'],
    categories: ['Men', 'Underwear'],
    tags: ['classic', 'soft', 'comfortable'],
    gender: 'men',
    productType: 'Brief',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Grey'],
    fabric: 'Cotton',
    material: 'Cotton',
    care: 'Machine wash',
    fit: 'Regular',
    pattern: 'Solid',
    supportLevel: 'Medium',
    padding: 'None',
    wireType: 'None',
    brand: 'MenClassic',
    seo: { title: 'Classic Men Brief', description: 'Classic men brief with soft fabric.' },
    published: true,
    featured: false,
  },

  // Women's products
  {
    title: 'Lace Underwire Bra',
    description: 'Elegant lace bra with underwire support and shaping design.',
    price: 1199,
    compareAtPrice: 1499,
    sku: 'LACE-UW-BRA-001',
    stock: 120,
    images: ['/assets/products/lace-lingerie.jpg'],
    categories: ['Women', 'Bras'],
    tags: ['lace', 'underwire', 'elegant'],
    gender: 'women',
    productType: 'Bra',
    sizes: ['32A', '32B', '34B', '34C', '36C', '36D'],
    colors: ['Black', 'Nude', 'Red'],
    fabric: 'Lace with Cotton Cup',
    material: 'Nylon/Spandex',
    care: 'Hand wash, line dry',
    fit: 'Regular',
    pattern: 'Lace',
    supportLevel: 'High',
    padding: 'None',
    wireType: 'Underwire',
    brand: 'ElegantLace',
    seo: { title: 'Lace Underwire Bra for Women', description: 'Elegant lace bra with excellent support.' },
    published: true,
    featured: true,
  },
  {
    title: 'Bamboo Fiber Briefs',
    description: 'Eco-friendly bamboo fiber briefs, soft and breathable.',
    price: 399,
    compareAtPrice: 499,
    sku: 'BAMBOO-BRIEF-001',
    stock: 180,
    images: ['/assets/products/red-lace-undergarment.jpg'],
    categories: ['Women', 'Innerwear'],
    tags: ['bamboo', 'eco-friendly', 'breathable'],
    gender: 'women',
    productType: 'Briefs',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Beige', 'Grey', 'Navy'],
    fabric: 'Bamboo Fiber',
    material: 'Bamboo/Spandex',
    care: 'Machine wash, tumble dry low',
    fit: 'Regular',
    pattern: 'Solid',
    supportLevel: 'Low',
    padding: 'None',
    wireType: 'None',
    brand: 'EcoComfort',
    seo: { title: 'Bamboo Fiber Briefs for Women', description: 'Eco-friendly bamboo fiber underwear.' },
    published: true,
    featured: false,
  },
  {
    title: 'Push-up Padded Bra',
    description: 'Push-up bra with light padding for enhanced shape and confidence.',
    price: 899,
    compareAtPrice: 1099,
    sku: 'PUSHUP-BRA-001',
    stock: 100,
    images: ['/assets/products/ladies-lingerie-top.jpg'],
    categories: ['Women', 'Bras'],
    tags: ['push-up', 'padded', 'shaping'],
    gender: 'women',
    productType: 'Bra',
    sizes: ['32B', '34B', '34C', '36C', '36D', '38D'],
    colors: ['Black', 'White', 'Peach'],
    fabric: 'Cotton Cup with Padding',
    material: 'Nylon/Spandex',
    care: 'Hand wash cold, air dry',
    fit: 'Regular',
    pattern: 'Solid',
    supportLevel: 'High',
    padding: 'Medium',
    wireType: 'None',
    brand: 'ShapeMe',
    seo: { title: 'Push-up Padded Bra for Women', description: 'Push-up bra with light padding for shaping.' },
    published: true,
    featured: false,
  },
  {
    title: 'Boyshort Panties',
    description: 'Comfortable boyshort with no VPL, perfect for any outfit.',
    price: 349,
    compareAtPrice: 449,
    sku: 'BOYSHORT-001',
    stock: 220,
    images: ['/assets/products/beige-lace-bralette.jpg'],
    categories: ['Women', 'Innerwear'],
    tags: ['boyshort', 'no-vpl', 'comfortable'],
    gender: 'women',
    productType: 'Boyshort',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Nude', 'White', 'Grey'],
    fabric: 'Smooth Microfiber',
    material: 'Microfiber',
    care: 'Machine wash warm',
    fit: 'Slim',
    pattern: 'Solid',
    supportLevel: 'Medium',
    padding: 'None',
    wireType: 'None',
    brand: 'SmoothFit',
    seo: { title: 'Boyshort Panties for Women', description: 'No-VPL boyshort for comfortable everyday wear.' },
    published: true,
    featured: false,
  },
];

async function run() {
  if (!process.env.MONGO_URI) {
    console.error('MONGO_URI not set');
    process.exit(1);
  }
  await mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
  console.log('Connected to MongoDB');

  for (const p of products) {
      // Fix image paths for men/women
      if (Array.isArray(p.images) && p.images.length > 0 && p.gender) {
        p.images = p.images.map(imgPath => {
          if (typeof imgPath === 'string') {
            if (p.gender === 'men' && !imgPath.includes('/men/')) {
              return imgPath.replace('/assets/products/', '/assets/products/men/');
            }
            if (p.gender === 'women' && !imgPath.includes('/women/')) {
              return imgPath.replace('/assets/products/', '/assets/products/women/');
            }
          }
          return imgPath;
        });
      }
      try {
        const product = new Product(p);
        const saved = await product.save();
        console.log('✓ Added:', saved.title, '(id:', saved._id.toString() + ')');
      } catch (err) {
        console.error('✗ Error:', p.title, err.message);
      }
  }

  await mongoose.disconnect();
  process.exit(0);
}

run().catch(err => { console.error(err); process.exit(1); });
